spring:
  application:
    name: yu-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 123456
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      database: 0
  session:
    store-type: redis
    timeout: 2592000s
    redis:
      namespace: yu-ai-code-mother:session
      flush-mode: on-save
  kafka:
    bootstrap-servers: 127.0.0.1:9092 # 替换为你的 Kafka 4.1 集群地址
    producer:
      # 重试次数，防止网络抖动导致消息丢失
      retries: 3
      # 消息确认机制：all (或 -1) 代表必须等待所有 ISR 副本确认，保证最高的数据安全性
      acks: all
      # 批量发送配置，提升吞吐量
      batch-size: 16384
      # 延迟发送时间（毫秒），允许在小时间窗口内收集更多消息一起发送
      properties:
        linger.ms: 5
      # 序列化器配置：Key 使用 String，Value 使用 Spring 提供的 JSON 序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8123
  servlet:
    context-path: /api/v1
    session:
      cookie:
        max-age: 2592000s
        http-only: true

  # LangChain4j Redis 配置（独立配置，避免与 Spring Data Redis 冲突）
app:
  langchain4j:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.chg.yuaicodemother.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn